site_name: Executable Workflow
repo_url: https://github.com/namuan/py-executable-checklist

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Introduction: 'index.md'
  - changelog.md

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true

plugins:
  - search:
