name: Draft a release

on:
  push:
    branches:
      - "**"

jobs:
  draft-release:
    if: "startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/python-poetry-env
      - name: Update version
        id: updated_version
        shell: bash
        run: |
          poetry version ${{ github.event.inputs.version }}
          version=$(poetry version --short)
          echo ::set-output name="version::$version"
      - name: Changelog
        id: changelog
        shell: bash
        run: |
          body=$(cat CHANGELOG.md)
          echo ::set-output name="body::$body"
      - name: Create a draft release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.updated_version.outputs.version }}
          release_name: Release ${{ steps.updated_version.outputs.version }}
          body: ${{ steps.changelog.outputs.body }}
          draft: true
